# TODO:: Follow TRITON concept
# TODO:: Simple copy concept in workspace to upload huge apps or datasets (and monitor folder events for add/delete)

workspace: /workspace/MONAI-label

apps:
  - deepgrow_2d: apps/deepgrow_2d
  - deepgrow_3d: apps/deepgrow_3d
  - segmentation_spleen: apps/segmentation_spleen

datasets:
  - msd_brain: datasets/msd_brain
  - msd_spleen: datasets/msd_spleen
