---
version: 1
name: Template App
description: MONAI Label App to provide active learning solution to label XYZ Organ
dimension: 3
labels:
  - XYZ
config:
  infer:
    device: cuda
  train:
    name: model_01
    device: cuda
    amp: false
    lr: 0.0001
    epochs: 1
